# Generated by Django 4.2.5 on 2023-12-21 01:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='models_instituciones',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)])),
            ],
        ),
        migrations.CreateModel(
            name='models_inscritos',
            fields=[
                ('id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)])),
                ('telefono', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('hora_inscripcion', models.TimeField()),
                ('estado', models.CharField(choices=[('reservado', 'RESERVADO'), ('completada', 'COMPLETADA'), ('anulada', 'ANULADA'), ('no asisten', 'NO ASISTEN')], max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=30)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='APP_FINAL.models_instituciones')),
            ],
        ),
    ]
