# Generated by Django 4.2.5 on 2023-12-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FINAL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_inscritos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='models_instituciones',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
