# Generated by Django 4.2.5 on 2023-12-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FINAL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_inscritos',
            name='hora_inscripcion',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
