# Generated by Django 4.2.5 on 2023-12-21 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FINAL', '0003_alter_models_inscritos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_inscritos',
            name='hora_inscripcion',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
