# Generated by Django 4.2.5 on 2023-12-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FINAL', '0004_alter_models_inscritos_hora_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_inscritos',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='models_instituciones',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
