# Generated by Django 4.2.5 on 2023-12-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FINAL', '0005_alter_models_inscritos_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_inscritos',
            name='observacion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
